-- L D MODERN EDUCATION ACADEMY — FINAL SAFE MIGRATION
-- Non-destructive / re-runnable. No DROP, TRUNCATE or data reset.

create table if not exists public.erp_number_sequences (
  kind text primary key,
  prefix text not null,
  last_value bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into public.erp_number_sequences(kind,prefix,last_value) values
 ('STUDENT','LDMS',0),('TEACHER','LDT',0),('LETTER','LDMEA/'||extract(year from current_date)::text||'/',0)
on conflict (kind) do nothing;

create or replace function public.ldmea_next_number(p_kind text)
returns text language plpgsql security definer set search_path=public as $$
declare k text:=upper(trim(p_kind)); n bigint; p text;
begin
  insert into public.erp_number_sequences(kind,prefix,last_value)
  values(k, case when k='STUDENT' then 'LDMS' when k='TEACHER' then 'LDT' when k='LETTER' then 'LDMEA/'||extract(year from current_date)::text||'/' else k||'-' end,0)
  on conflict(kind) do nothing;
  update public.erp_number_sequences set last_value=last_value+1,updated_at=now() where kind=k returning last_value,prefix into n,p;
  return p||lpad(n::text,6,'0');
end $$;

create table if not exists public.official_letters (
 id bigint generated by default as identity primary key,
 letter_no text not null unique,
 letter_date date,
 template_name text,
 recipient text,
 recipient_address text,
 subject text,
 reference_text text,
 body_text text,
 copy_to text,
 signatory text,
 linked_student_id text,
 linked_teacher_id text,
 status text not null default 'Issued',
 created_by uuid,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists official_letters_date_idx on public.official_letters(letter_date desc);
create index if not exists official_letters_subject_idx on public.official_letters(subject);

-- Add central signatory settings only when school_settings exists.
do $$ begin
 if to_regclass('public.school_settings') is not null then
   alter table public.school_settings add column if not exists principal_signature_url text;
   alter table public.school_settings add column if not exists principal_signature_path text;
   alter table public.school_settings add column if not exists authorized_signatory_name text;
   alter table public.school_settings add column if not exists authorized_signatory_title text;
   alter table public.school_settings add column if not exists teacher_id_card_enabled boolean not null default false;
 end if;
end $$;

-- Optional generated public IDs: only add when the corresponding tables exist.
do $$ begin
 if to_regclass('public.students') is not null then
   alter table public.students add column if not exists student_id text;
   create unique index if not exists students_student_id_unique_nonblank on public.students(student_id) where student_id is not null and btrim(student_id)<>'';
 end if;
 if to_regclass('public.teacher_profiles') is not null then
   alter table public.teacher_profiles add column if not exists employee_id text;
   create unique index if not exists teacher_profiles_employee_id_unique_nonblank on public.teacher_profiles(employee_id) where employee_id is not null and btrim(employee_id)<>'';
 end if;
end $$;

-- Safe auto-number triggers for NEW rows only. Existing values are preserved.
create or replace function public.ldmea_students_auto_id() returns trigger language plpgsql as $$
begin
 if new.student_id is null or btrim(new.student_id)='' then new.student_id:=public.ldmea_next_number('STUDENT'); end if;
 return new;
end $$;
create or replace function public.ldmea_teachers_auto_id() returns trigger language plpgsql as $$
begin
 if new.employee_id is null or btrim(new.employee_id)='' then new.employee_id:=public.ldmea_next_number('TEACHER'); end if;
 return new;
end $$;
do $$ begin
 if to_regclass('public.students') is not null then
   if not exists(select 1 from pg_trigger where tgname='trg_ldmea_students_auto_id') then execute 'create trigger trg_ldmea_students_auto_id before insert on public.students for each row execute function public.ldmea_students_auto_id()'; end if;
 end if;
 if to_regclass('public.teacher_profiles') is not null then
   if not exists(select 1 from pg_trigger where tgname='trg_ldmea_teachers_auto_id') then execute 'create trigger trg_ldmea_teachers_auto_id before insert on public.teacher_profiles for each row execute function public.ldmea_teachers_auto_id()'; end if;
 end if;
end $$;

-- NOTE: RLS policies are intentionally not weakened here. Existing production RLS remains authoritative.
-- Run this migration first; then deploy the matching HTML. If your Admin role cannot insert official_letters,
-- add a policy matching your EXISTING Admin-role convention rather than opening the table to anon users.

-- V64.17 final compatibility: staff is the active teacher/staff master in this frontend.
do $$ begin
 if to_regclass('public.staff') is not null then
   alter table public.staff add column if not exists employee_id text;
   create unique index if not exists staff_employee_id_unique_nonblank on public.staff(employee_id) where employee_id is not null and btrim(employee_id)<>'';
   if not exists(select 1 from pg_trigger where tgname='trg_ldmea_staff_auto_id') then
     execute 'create trigger trg_ldmea_staff_auto_id before insert on public.staff for each row execute function public.ldmea_teachers_auto_id()';
   end if;
 end if;
end $$;
