const SUPABASE_URL=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
function send(res,status,obj){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('X-Content-Type-Options','nosniff');res.end(JSON.stringify(obj))}
async function asJson(r){const t=await r.text();try{return t?JSON.parse(t):null}catch{return {raw:t}}}
async function rows(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY}}),j=await asJson(r);if(!r.ok)throw new Error(j?.message||j?.error||'Database lookup failed');return Array.isArray(j)?j:[]}
async function verifyUser(req){const auth=String(req.headers.authorization||'');if(!auth.startsWith('Bearer '))throw Object.assign(new Error('Login required'),{status:401});const r=await fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:SERVICE_KEY,Authorization:auth}});if(!r.ok)throw Object.assign(new Error('Invalid/expired session'),{status:401});return {user:await r.json(),auth}}
async function ensureStudentBucket(){const h={apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json'},base=SUPABASE_URL+'/storage/v1/bucket';let r=await fetch(base+'/student-media',{headers:h});if(r.ok)return;if(r.status!==404){const j=await asJson(r);throw new Error(j?.message||'Student storage check failed')}r=await fetch(base,{method:'POST',headers:h,body:JSON.stringify({id:'student-media',name:'student-media',public:false})});if(!r.ok&&r.status!==409){const j=await asJson(r);throw new Error(j?.message||'student-media bucket create failed')}}
async function authorizeStudent(uid,studentId){const p=(await rows(`profiles?id=eq.${encodeURIComponent(uid)}&select=role,status&limit=1`))[0];const role=String(p?.role||'').toLowerCase(),st=String(p?.status||'active').toLowerCase();if(!p||['disabled','inactive','pending','suspended','rejected'].includes(st))throw Object.assign(new Error('Account inactive'),{status:403});const s=(await rows(`students?id=eq.${encodeURIComponent(studentId)}&select=id,admission_no,class_name,student_name&limit=1`))[0];if(!s)throw new Error('Student not found');if(['admin','super_admin','principal','admission'].includes(role))return {s,role};if(role!=='teacher')throw Object.assign(new Error('Teacher/Admin only'),{status:403});const tp=(await rows(`teacher_profiles?auth_user_id=eq.${encodeURIComponent(uid)}&select=id,approval_status,is_active&limit=1`))[0];if(!tp||String(tp.approval_status||'').toLowerCase()!=='approved'||tp.is_active===false)throw Object.assign(new Error('Teacher access not approved'),{status:403});const ca=await rows(`teacher_class_assignments?teacher_profile_id=eq.${encodeURIComponent(tp.id)}&class_name=eq.${encodeURIComponent(s.class_name)}&is_active=eq.true&select=id&limit=1`);if(!ca[0])throw Object.assign(new Error('Student class is not assigned to this Teacher'),{status:403});return {s,role}}
async function uploadObject(path,buf){const h={apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'image/jpeg','x-upsert':'true','Cache-Control':'3600'};const r=await fetch(SUPABASE_URL+'/storage/v1/object/student-media/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:h,body:buf}),j=await asJson(r);if(!r.ok)throw new Error(j?.message||j?.error||'Student photo upload failed')}
async function callPhotoRpc(auth,studentId,path){const r=await fetch(SUPABASE_URL+'/rest/v1/rpc/v91_teacher_set_student_photo',{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:auth,'Content-Type':'application/json'},body:JSON.stringify({p_student_id:studentId,p_photo_path:path})}),j=await asJson(r);if(!r.ok)throw new Error(j?.message||j?.error||'Student photo sync failed');return j}
async function signedUrl(path){const r=await fetch(SUPABASE_URL+'/storage/v1/object/sign/student-media/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})}),j=await asJson(r);if(!r.ok)return '';let u=j?.signedURL||j?.signedUrl||j?.signed_url||'';if(u&&u.startsWith('/'))u=SUPABASE_URL+'/storage/v1'+u;return u}
module.exports=async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'POST only'});if(!SUPABASE_URL||!SERVICE_KEY)return send(res,500,{error:'Supabase server environment is not configured'});try{const {user,auth}=await verifyUser(req),body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),studentId=String(body.student_id||''),b64=String(body.file_base64||'');if(!studentId||!b64)throw new Error('Student/photo required');const {s,role}=await authorizeStudent(user.id,studentId);let buf=Buffer.from(b64,'base64');if(!buf.length||buf.length>80*1024)throw new Error('Photo must be optimized below 80 KB');await ensureStudentBucket();const folder=role==='teacher'?'teacher-student-photo':'admin-student-photo',path=`${folder}/${user.id}/${s.id}.jpg`;await uploadObject(path,buf);await callPhotoRpc(auth,s.id,path);return send(res,200,{ok:true,path,signed_url:await signedUrl(path),student_name:s.student_name,admission_no:s.admission_no})}catch(e){return send(res,e.status||400,{error:e.message||String(e)})}}
