-- V60 non-destructive Smart Admit Card tracking. Session persistence is client-side; no auth reset here.
create table if not exists public.v60_admit_issues (
 id uuid primary key default gen_random_uuid(),
 exam_id uuid not null,
 student_key text not null,
 student_name text,
 class_name text,
 admission_no text,
 issue_status text not null default 'issued' check (issue_status in ('issued','override_issued','cancelled')),
 issued_by uuid,
 issued_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(exam_id,student_key)
);
create index if not exists v60_admit_issues_exam_idx on public.v60_admit_issues(exam_id);
create index if not exists v60_admit_issues_class_idx on public.v60_admit_issues(class_name);
create table if not exists public.v60_admit_issue_history (
 id bigint generated by default as identity primary key,
 exam_id uuid not null,
 student_key text not null,
 action text not null check (action in ('ISSUED','REPRINT','CANCELLED','OVERRIDE')),
 action_by uuid,
 action_at timestamptz not null default now()
);
create index if not exists v60_admit_hist_exam_idx on public.v60_admit_issue_history(exam_id,action_at desc);
alter table public.v60_admit_issues enable row level security;
alter table public.v60_admit_issue_history enable row level security;
do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='v60_admit_issues' and policyname='v60_admit_read_authenticated') then
  create policy v60_admit_read_authenticated on public.v60_admit_issues for select to authenticated using (true);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='v60_admit_issues' and policyname='v60_admit_admin_write') then
  create policy v60_admit_admin_write on public.v60_admit_issues for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','super_admin','principal'))) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','super_admin','principal')));
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='v60_admit_issue_history' and policyname='v60_admit_hist_read_authenticated') then
  create policy v60_admit_hist_read_authenticated on public.v60_admit_issue_history for select to authenticated using (true);
 end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='v60_admit_issue_history' and policyname='v60_admit_hist_admin_write') then
  create policy v60_admit_hist_admin_write on public.v60_admit_issue_history for insert to authenticated with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role in ('admin','super_admin','principal')));
 end if;
end $$;
