-- V53 COMPLETE CONSOLIDATION — additive / idempotent / non-destructive
create extension if not exists pgcrypto;
create table if not exists public.erp_number_counters(kind text not null, academic_session text not null default '', last_no bigint not null default 0, updated_at timestamptz not null default now(), primary key(kind,academic_session));
create or replace function public.erp_next_number(p_kind text,p_session text default '2026-27',p_prefix text default null) returns text language plpgsql security definer set search_path=public as $$ declare n bigint; pref text; begin insert into erp_number_counters(kind,academic_session,last_no) values(p_kind,coalesce(p_session,''),1) on conflict(kind,academic_session) do update set last_no=erp_number_counters.last_no+1,updated_at=now() returning last_no into n; pref:=coalesce(p_prefix,upper(left(p_kind,3))); return pref||'/'||replace(coalesce(p_session,''),'/','-')||'/'||lpad(n::text,5,'0'); end $$;
create table if not exists public.report_audit(id uuid primary key default gen_random_uuid(),report_type text not null,date_from date,date_to date,generated_by uuid,created_at timestamptz not null default now());
create table if not exists public.parent_password_requests(id uuid primary key default gen_random_uuid(),parent_user_id uuid,admission_no text,request_note text,status text not null default 'Pending',resolved_by uuid,resolved_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.teacher_self_attendance(id uuid primary key default gen_random_uuid(),teacher_user_id uuid not null,attendance_date date not null default current_date,status text not null default 'Present',confirmed_at timestamptz not null default now(),unique(teacher_user_id,attendance_date));
create table if not exists public.my_notes(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null,title text not null,body text,tags text,is_pinned boolean not null default false,note_date date not null default current_date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.parent_notes(id uuid primary key default gen_random_uuid(),admission_no text not null,parent_user_id uuid,note text not null,note_date date not null default current_date,created_at timestamptz not null default now());
create table if not exists public.student_roster_requests(id uuid primary key default gen_random_uuid(),teacher_user_id uuid,admission_no text,class_name text,request_type text not null check(request_type in('ADD','REMOVE')),reason text,status text not null default 'Pending',reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.official_report_settings(id int primary key default 1,school_name text default 'L D MODERN EDUCATION ACADEMY',address text default 'Gambhiriya Bujurg, Singhapatti, Padrauna, Kushinagar, Uttar Pradesh',principal_name text default 'Adv. Shiv Balak Yadav',updated_at timestamptz not null default now());
insert into public.official_report_settings(id) values(1) on conflict(id) do nothing;
-- Helpful uniqueness only when clean; guarded to avoid breaking old production data.
do $$ begin if not exists(select 1 from pg_indexes where schemaname='public' and indexname='ux_teacher_self_attendance_day') then create unique index ux_teacher_self_attendance_day on public.teacher_self_attendance(teacher_user_id,attendance_date); end if; exception when others then raise notice 'teacher attendance index skipped: %',sqlerrm; end $$;
-- RLS enabled; existing project auth policies remain authoritative. Service/admin paths can still operate per existing project configuration.
alter table public.parent_password_requests enable row level security; alter table public.teacher_self_attendance enable row level security; alter table public.my_notes enable row level security; alter table public.parent_notes enable row level security; alter table public.student_roster_requests enable row level security;
