(()=>{
'use strict';
const categories={
'Teaching Exams':['CTET Paper 1','CTET Paper 2','UPTET','Super TET','UP Primary Teacher','Bihar Primary Teacher','BPSC TRE','KVS','NVS','DSSSB','REET','State Teacher Exam'],
'State PCS':['UPPSC','BPSC','MPPSC','RPSC','UKPSC','State PCS'],
'SSC':['SSC CGL','SSC CHSL','SSC MTS','SSC GD','SSC CPO','SSC Selection Post'],
'Railway':['RRB NTPC','RRB Group D','RRB ALP','RRB Technician','Railway Exam'],
'Banking':['IBPS PO','IBPS Clerk','SBI PO','SBI Clerk','RRB Bank PO','RRB Bank Clerk'],
'Police / Defence':['UP Police','Bihar Police','SI','Constable','NDA','CDS','Agniveer','Defence Exam'],
'Entrance Exams':['CUET','Polytechnic','B.Ed Entrance','D.El.Ed Entrance','Entrance Exam'],
'General Competition':['General Studies','General Knowledge','Current Affairs','Reasoning','Mathematics','Hindi','English','Computer','Science','Geography','History','Polity','Economy','Environment']
};
const subjectMap={
'Mathematics':{'Arithmetic':['Number System','Simplification','Percentage','Profit and Loss','Ratio and Proportion','Average','Simple Interest','Compound Interest','Time and Work','Time Speed Distance'],'Algebra':['Linear Equations','Basic Algebraic Identities'],'Mensuration':['2D Mensuration','3D Mensuration'],'Data':['Data Interpretation']},
'Reasoning':{'Verbal Reasoning':['Analogy','Classification','Series','Coding-Decoding','Blood Relation','Direction Test','Ranking'],'Non-Verbal':['Figure Series','Mirror and Water Image'],'Logical':['Syllogism','Statement and Conclusion']},
'General Studies':{'Polity':['Constitution Basics','Fundamental Rights','Directive Principles','Parliament','President and Governor'],'History':['Ancient India Overview','Medieval India Overview','Revolt of 1857','Indian National Movement'],'Geography':['India Physical Features','Indian Rivers','Climate of India','Soils of India'],'Economy':['Basic Economics','National Income','Inflation','Budget Basics'],'Science':['Cell','Human Body Basics','Force and Motion','Acids Bases and Salts'],'Environment':['Ecology Basics','Biodiversity','Pollution']},
'General Knowledge':{'Static GK':['Important Organizations','Books and Authors','Awards','Sports Basics','Important Days'],'India':['National Symbols','States and Capitals']},
'Current Affairs':{'Current':['Daily Current Affairs','Weekly Current Affairs','Monthly Current Affairs','Exam-wise Current Affairs','State-wise Current Affairs']},
'Hindi':{'व्याकरण':['संधि','समास','पर्यायवाची','विलोम','मुहावरे','वाक्य शुद्धि'],'बोध':['गद्यांश','शब्द ज्ञान']},
'English':{'Grammar':['Parts of Speech','Subject-Verb Agreement','Tense','Articles','Prepositions','Error Detection'],'Vocabulary':['Synonym','Antonym','Idioms and Phrases','One Word Substitution'],'Reading':['Cloze Test','Reading Comprehension']},
'Computer':{'Basics':['Computer Fundamentals','Hardware and Software','Operating System','MS Office Basics','Internet and Networking','Cyber Safety']},
'Child Development & Pedagogy':{'CDP':['Growth and Development','Piaget','Vygotsky','Learning Theories','Individual Differences','Inclusive Education','Assessment'],'Education':['RTE Basics','Classroom Management','Teaching Methods']},
'Science':{'Physics':['Motion','Force','Work and Energy','Electricity'],'Chemistry':['Matter','Atom and Molecule','Acid Base Salt'],'Biology':['Cell','Human Systems','Nutrition','Disease']},
'Polity':{'Constitution':['Preamble','Fundamental Rights','Directive Principles','Fundamental Duties','Amendment Process'],'Institutions':['Parliament','President','Prime Minister','Supreme Court','Election Commission']},
'History':{'Modern India':['Revolt of 1857','Socio Religious Reform','Indian National Congress','Gandhian Era','Freedom and Partition'],'Ancient/Medieval':['Ancient India Overview','Medieval India Overview']},
'Geography':{'India':['Physical Divisions','Rivers','Climate','Soils','Agriculture'],'World':['Latitude Longitude','Earth Interior','Atmosphere']},
'Economy':{'Basics':['Demand and Supply','Inflation','National Income','Fiscal Policy','Monetary Policy'],'India':['Budget','Banking Basics','Poverty and Employment']},
'Environment':{'Ecology':['Ecosystem','Food Chain','Biodiversity','Protected Areas','Pollution','Climate Change']}
};
const examSubjects={
'CTET Paper 1':['Child Development & Pedagogy','Mathematics','Hindi','English','Science'],
'CTET Paper 2':['Child Development & Pedagogy','Mathematics','Science','Hindi','English','General Studies'],
'UPTET':['Child Development & Pedagogy','Mathematics','Hindi','English','General Studies'],
'Super TET':['Mathematics','Reasoning','General Studies','Hindi','English','Child Development & Pedagogy'],
'UP Primary Teacher':['Mathematics','Reasoning','General Studies','Hindi','English','Child Development & Pedagogy','Current Affairs'],
'Bihar Primary Teacher':['Mathematics','Reasoning','General Studies','Hindi','English','Child Development & Pedagogy','Current Affairs'],
'BPSC TRE':['Mathematics','Reasoning','General Studies','Hindi','English','Child Development & Pedagogy','Current Affairs'],
'KVS':['Reasoning','General Studies','Hindi','English','Child Development & Pedagogy','Computer','Current Affairs'],
'NVS':['Reasoning','General Studies','Hindi','English','Child Development & Pedagogy','Computer','Current Affairs'],
'DSSSB':['Reasoning','General Studies','Hindi','English','Mathematics','Current Affairs'],
'REET':['Child Development & Pedagogy','Mathematics','Hindi','English','General Studies','Current Affairs'],
'UPPSC':['General Studies','Polity','History','Geography','Economy','Environment','Science','Current Affairs'],
'BPSC':['General Studies','Polity','History','Geography','Economy','Science','Current Affairs'],
'MPPSC':['General Studies','Polity','History','Geography','Economy','Environment','Current Affairs'],
'RPSC':['General Studies','Polity','History','Geography','Economy','Current Affairs'],
'UKPSC':['General Studies','Polity','History','Geography','Economy','Environment','Current Affairs'],
'State PCS':['General Studies','Polity','History','Geography','Economy','Environment','Science','Current Affairs'],
'SSC CGL':['Mathematics','Reasoning','General Studies','English','Current Affairs'],
'SSC CHSL':['Mathematics','Reasoning','General Studies','English','Current Affairs'],
'SSC MTS':['Mathematics','Reasoning','General Studies','English','Current Affairs'],
'SSC GD':['Mathematics','Reasoning','General Studies','Hindi','English','Current Affairs'],
'SSC CPO':['Mathematics','Reasoning','General Studies','English','Current Affairs'],
'SSC Selection Post':['Mathematics','Reasoning','General Studies','English','Current Affairs'],
'RRB NTPC':['Mathematics','Reasoning','General Studies','Current Affairs'],
'RRB Group D':['Mathematics','Reasoning','General Studies','Science','Current Affairs'],
'RRB ALP':['Mathematics','Reasoning','Science','General Studies','Current Affairs'],
'RRB Technician':['Mathematics','Reasoning','Science','General Studies','Current Affairs'],
'Railway Exam':['Mathematics','Reasoning','General Studies','Science','Current Affairs'],
'IBPS PO':['Mathematics','Reasoning','English','Current Affairs','Computer'],
'IBPS Clerk':['Mathematics','Reasoning','English','Current Affairs','Computer'],
'SBI PO':['Mathematics','Reasoning','English','Current Affairs','Computer'],
'SBI Clerk':['Mathematics','Reasoning','English','Current Affairs','Computer'],
'RRB Bank PO':['Mathematics','Reasoning','English','Current Affairs','Computer'],
'RRB Bank Clerk':['Mathematics','Reasoning','English','Current Affairs','Computer'],
'UP Police':['Mathematics','Reasoning','General Studies','Hindi','Current Affairs'],
'Bihar Police':['Mathematics','Reasoning','General Studies','Hindi','Current Affairs'],
'SI':['Mathematics','Reasoning','General Studies','Hindi','English','Current Affairs'],
'Constable':['Mathematics','Reasoning','General Studies','Hindi','Current Affairs'],
'NDA':['Mathematics','English','General Studies','Science','Current Affairs'],
'CDS':['English','General Studies','Mathematics','Current Affairs'],
'Agniveer':['Mathematics','Reasoning','General Studies','Science','English','Current Affairs'],
'Defence Exam':['Mathematics','Reasoning','General Studies','Science','English','Current Affairs'],
'CUET':['English','General Studies','Mathematics','Reasoning','Current Affairs'],
'Polytechnic':['Mathematics','Science','Reasoning'],
'B.Ed Entrance':['General Studies','Reasoning','Hindi','English','Child Development & Pedagogy','Current Affairs'],
'D.El.Ed Entrance':['General Studies','Reasoning','Hindi','English','Child Development & Pedagogy','Current Affairs'],
'Entrance Exam':['General Studies','Reasoning','Mathematics','English','Current Affairs'],
'General Studies':['General Studies','Current Affairs'],'General Knowledge':['General Knowledge','Current Affairs'],'Current Affairs':['Current Affairs'],'Reasoning':['Reasoning'],'Mathematics':['Mathematics'],'Hindi':['Hindi'],'English':['English'],'Computer':['Computer'],'Science':['Science'],'Geography':['Geography'],'History':['History'],'Polity':['Polity'],'Economy':['Economy'],'Environment':['Environment']
};
const genericCore={
'Mathematics':{overview:'Concept → formula/method → solved example → exam practice.',facts:['Base value पहचानना जरूरी है.','Units और conditions ध्यान से पढ़ें.'],mistakes:['Wrong base लेना','Calculation जल्दी में गलत करना'],trap:'Language में “of”, “more than”, “less than” और successive change को ध्यान से पढ़ें.'},
'Reasoning':{overview:'Pattern पहचानें, method बनाएं, फिर speed practice करें.',facts:['पहले pattern family पहचानें.','Accuracy के बाद speed बढ़ाएँ.'],mistakes:['Pattern जल्दी assume करना','Direction/order notation न बनाना'],trap:'Question setter similar-looking options दे सकता है.'},
'English':{overview:'Rule को context और question pattern के साथ सीखें.',facts:['Grammar rule के साथ exception भी verify करें.'],mistakes:['Sentence context ignore करना'],trap:'Near-correct option और usage trap.'},
'Hindi':{overview:'नियम → उदाहरण → अपवाद → परीक्षा प्रश्न.',facts:['शब्द/वाक्य का संदर्भ देखें.'],mistakes:['नियम याद पर प्रयोग नहीं'],trap:'मिलते-जुलते विकल्पों में सूक्ष्म अंतर.'},
'General Studies':{overview:'Concept + chronology/comparison + exam facts.',facts:['Fact/date को verified source से lock करें.'],mistakes:['Unverified date याद करना'],trap:'Statement-based प्रश्न में absolute words देखें.'},
'Polity':{overview:'Constitutional concept → provision → institution → comparison → questions.',facts:['Article/Amendment संख्या केवल verified source से पढ़ाएँ.'],mistakes:['Article और related provision mix करना'],trap:'Statement wording में power/authority का subtle difference.'},
'History':{overview:'Timeline → cause → event → result → exam facts.',facts:['Date/person को source-verified रखें.'],mistakes:['Chronology mix करना'],trap:'Similar events/persons/dates.'},
'Geography':{overview:'Concept → map/location → physical relation → facts → map questions.',facts:['Map orientation और location relation जरूरी है.'],mistakes:['Location facts बिना map के याद करना'],trap:'River/source/tributary/location confusion.'},
'Science':{overview:'Basic concept → definition → diagram → daily-life example → MCQ.',facts:['Scientific fact/formula को textbook/official source से verify करें.'],mistakes:['Definition और example mix करना'],trap:'Unit, condition या exception छूटना.'},
'Child Development & Pedagogy':{overview:'Theory → psychologist/principle → classroom example → confusing options.',facts:['Theory को classroom application से जोड़ें.'],mistakes:['Psychologists की theories mix करना'],trap:'Option में partially correct statement.'},
'Current Affairs':{overview:'Event → important point → exam question → MCQ.',facts:['Date/source freshness mandatory.'],mistakes:['Old news को current मानना'],trap:'Similar names, dates, places.'}
};
const verifiedTopics={
'Percentage':(window.SKY_SHARED_CONTENT&&window.SKY_SHARED_CONTENT.Percentage)?{...window.SKY_SHARED_CONTENT.Percentage}:{subject:'Mathematics',chapter:'Arithmetic',status:'NEEDS REVIEW',overview:'Shared Percentage content not loaded.'},
'Piaget':{subject:'Child Development & Pedagogy',chapter:'CDP',status:'NEEDS REVIEW',overview:'Piaget ने cognitive development को stages में समझाया.',relevance:'Teacher eligibility/recruitment exams में stage, age-range, classroom implication और concept-based options पूछे जाते हैं.',mapping:'CDP → Cognitive Development',basic:['Development qualitatively different stages से गुजरता है.','Learning में active construction महत्वपूर्ण है.'],theory:['Sensorimotor, Preoperational, Concrete Operational, Formal Operational — standard sequence.','Exact age bands and terminology should be matched with the chosen authoritative pedagogy source before publication.'],script:['पहले बच्चे की सोच और adult thinking का difference पूछें.','Stage order समझाएँ.','Classroom example से concrete vs abstract समझाएँ.'],board:['Piaget → Cognitive Development','Stage sequence','Classroom application'],notes:['Child actively constructs knowledge.','Readiness और developmental level का ध्यान रखें.'],deep:['Assimilation और accommodation जैसे concepts को example से पढ़ाएँ.'],facts:['Stage sequence exam-relevant है.'],formula:[],tricks:['Stage order को concept से याद करें, केवल mnemonic पर निर्भर न रहें.'],examples:['Concrete material से class activity','Hypothetical reasoning का higher-level example'],commonMistakes:['Age-range या stage feature को दूसरे stage से mix करना.'],oneLine:['Piaget = cognitive development + active learner'],homework:['4 stage features का comparison chart'],dpp:['Stage-feature matching','Classroom application MCQ'],mcqs:[{q:'Piaget मुख्यतः किस development से जुड़े हैं?',o:['Cognitive','Physical only','Language only','Moral only'],a:0,e:'Piaget का प्रमुख framework cognitive development है.'}]},
'Subject-Verb Agreement':{subject:'English',chapter:'Grammar',status:'NEEDS REVIEW',overview:'Subject और finite verb का number/person के अनुसार agreement.',relevance:'SSC, Banking, teaching और entrance exams में error detection/sentence correction में frequent pattern.',mapping:'English Grammar → Subject-Verb Agreement',basic:['Singular subject generally takes singular verb form in present tense.','Plural subject generally takes plural verb form.'],theory:['Actual subject identify करें; बीच के phrase से confuse न हों.','Compound subjects और special structures अलग rules मांगते हैं.'],script:['Sentence में पहले true subject circle करें.','Verb locate करें.','Number/person match कराएँ.'],board:['Find Subject → Find Verb → Match Number/Person'],notes:['Ignore intervening phrase while finding agreement.'],deep:['Collective nouns, either/or, neither/nor and quantities need context-specific rules.'],facts:[],formula:[],tricks:['Verb से पहले nearest noun को हमेशा subject न मानें.'],examples:['The list of items is long.','The players are ready.'],commonMistakes:['Nearest noun attraction error.'],oneLine:['Agreement follows the grammatical subject.'],homework:['10 error detection items'],dpp:['5 correction + 5 fill-in items'],mcqs:[{q:'The list of books ___ on the table.',o:['are','is','were','have'],a:1,e:'Subject “list” singular है.'}]},
'Cell':{subject:'Science',chapter:'Biology',status:'NEEDS REVIEW',overview:'Cell जीवों की structural and functional basic unit है.',relevance:'School/competition science में cell structure, organelles और plant-animal comparison पूछे जाते हैं.',mapping:'Biology → Cell',basic:['Cell living organisms की basic structural-functional unit है.','Different cells have specialized structures/functions.'],theory:['Cell membrane, cytoplasm और genetic material core ideas हैं.','Organelle details prescribed syllabus/textbook के अनुसार पढ़ाएँ.'],script:['Room/building analogy से organization समझाएँ.','Plant vs animal cell visual comparison दिखाएँ.'],board:['Cell → membrane + cytoplasm + genetic material','Plant vs Animal comparison'],notes:['Structure supports function.'],deep:['Prokaryotic/eukaryotic comparison higher level में जोड़ा जा सकता है.'],facts:[],formula:[],tricks:[],examples:['Onion peel observation','Cheek cell observation'],commonMistakes:['Cell wall और cell membrane को same मानना.'],oneLine:['Cell = basic structural and functional unit of life'],homework:['Plant-animal cell labelled comparison'],dpp:['Organelle-function match'],mcqs:[{q:'जीवों की basic structural and functional unit?',o:['Tissue','Cell','Organ','System'],a:1,e:'Cell basic unit है.'}]}
};
const vocabSeed=[
['abate','əˈbeɪt','कम होना/करना','become less intense','decrease','intensify','The storm began to abate.'],
['aberration','ˌæbəˈreɪʃən','विचलन','departure from what is normal','deviation','normality','The result was an aberration.'],
['benevolent','bəˈnevələnt','परोपकारी','kind and generous','kind','malevolent','A benevolent leader helped the community.'],
['candid','ˈkændɪd','स्पष्टवादी','truthful and straightforward','frank','evasive','She gave a candid answer.'],
['diligent','ˈdɪlɪdʒənt','परिश्रमी','careful and persistent','industrious','negligent','A diligent student revises daily.'],
['eloquent','ˈeləkwənt','वाक्पटु','fluent and persuasive','expressive','inarticulate','The speaker was eloquent.'],
['frugal','ˈfruːɡəl','मितव्ययी','economical with money/resources','thrifty','extravagant','A frugal family avoids waste.'],
['gregarious','ɡrɪˈɡeəriəs','मिलनसार','fond of company','sociable','reserved','He is gregarious at gatherings.'],
['meticulous','məˈtɪkjələs','अत्यंत सावधान','very careful about details','careful','careless','She kept meticulous records.'],
['pragmatic','præɡˈmætɪk','व्यावहारिक','dealing with problems practically','practical','idealistic','They chose a pragmatic solution.'],
['arduous','ˈɑːdjuəs','कठिन','requiring great effort','difficult','easy','The climb was arduous.'],
['bolster','ˈbəʊlstə','मजबूत करना','support or strengthen','strengthen','weaken','Evidence bolstered the claim.'],
['concise','kənˈsaɪs','संक्षिप्त','brief but complete','brief','verbose','Write a concise answer.'],
['deter','dɪˈtɜː','रोकना','discourage from an action','discourage','encourage','Strict rules may deter cheating.'],
['emulate','ˈemjuleɪt','अनुकरण करना','try to match or surpass','imitate','ignore','Students emulate good habits.'],
['feasible','ˈfiːzəbəl','व्यवहार्य','possible and practical','practicable','impossible','The plan is feasible.'],
['hostile','ˈhɒstaɪl','शत्रुतापूर्ण','unfriendly or aggressive','unfriendly','friendly','The crowd became hostile.'],
['impartial','ɪmˈpɑːʃəl','निष्पक्ष','fair and unbiased','fair','biased','A judge must remain impartial.'],
['jubilant','ˈdʒuːbɪlənt','अत्यंत प्रसन्न','feeling great joy','joyful','dejected','Fans were jubilant after the win.'],
['lucid','ˈluːsɪd','स्पष्ट','clear and easy to understand','clear','confusing','The teacher gave a lucid explanation.'],
['novice','ˈnɒvɪs','नवशिक्षु','a beginner','beginner','expert','A novice needs guided practice.'],
['obsolete','ˈɒbsəliːt','अप्रचलित','no longer in use','outdated','current','The old device became obsolete.'],
['plausible','ˈplɔːzəbəl','विश्वसनीय लगने वाला','seemingly reasonable','credible','implausible','The explanation sounds plausible.'],
['reconcile','ˈrekənsaɪl','मेल कराना','restore agreement or consistency','harmonize','conflict','We reconciled the two records.'],
['scrutinize','ˈskruːtənaɪz','बारीकी से जाँचना','examine closely','inspect','overlook','Scrutinize the data before submitting.'],
['tenacious','təˈneɪʃəs','दृढ़','persistent and determined','persistent','yielding','She was tenacious in preparation.'],
['unanimous','juːˈnænɪməs','सर्वसम्मत','fully agreed','agreed','divided','The decision was unanimous.'],
['vigilant','ˈvɪdʒɪlənt','सतर्क','watchful for danger','alert','careless','Remain vigilant during verification.'],
['wary','ˈweəri','सावधान','cautious about risk','cautious','reckless','Be wary of unverified claims.'],
['zealous','ˈzeləs','उत्साही','very enthusiastic','enthusiastic','apathetic','He is zealous about learning.'],
['augment','ɔːɡˈment','बढ़ाना','make greater','increase','reduce','Training can augment skills.'],
['coherent','kəʊˈhɪərənt','सुसंगत','logical and consistent','logical','incoherent','Give a coherent explanation.'],
['deplete','dɪˈpliːt','कम कर देना','use up or reduce','exhaust','replenish','Overuse can deplete resources.'],
['elusive','ɪˈluːsɪv','पकड़ में न आने वाला','difficult to find or achieve','slippery','obvious','The exact cause remained elusive.'],
['foster','ˈfɒstə','प्रोत्साहित करना','encourage development','encourage','hinder','Good feedback fosters learning.'],
['hamper','ˈhæmpə','बाधा डालना','hinder progress','hinder','assist','Noise can hamper concentration.'],
['intricate','ˈɪntrɪkət','जटिल','very detailed and complicated','complex','simple','The pattern is intricate.'],
['mitigate','ˈmɪtɪɡeɪt','कम करना','make less severe','alleviate','aggravate','Trees help mitigate heat.'],
['notion','ˈnəʊʃən','धारणा','an idea or belief','idea','fact','The notion needs evidence.'],
['perpetual','pəˈpetʃuəl','निरंतर','continuing for a long time','continuous','temporary','Perpetual change requires adaptation.'],
['resilient','rɪˈzɪliənt','लचीला/सहनीय','able to recover quickly','strong','fragile','Resilient learners recover from setbacks.'],
['substantiate','səbˈstænʃieɪt','प्रमाणित करना','support with evidence','verify','refute','Substantiate the answer with facts.'],
['transient','ˈtrænziənt','क्षणिक','lasting a short time','temporary','permanent','The effect was transient.'],
['validate','ˈvælɪdeɪt','सत्यापित करना','check or prove validity','verify','invalidate','Validate the source before teaching.'],
['adverse','ˈædvɜːs','प्रतिकूल','harmful or unfavorable','unfavorable','favorable','Adverse weather delayed travel.'],
['conspicuous','kənˈspɪkjuəs','स्पष्ट दिखने वाला','easy to notice','noticeable','inconspicuous','The error was conspicuous.'],
['disseminate','dɪˈsemɪneɪt','प्रसारित करना','spread information widely','circulate','conceal','Schools disseminate notices.'],
['innate','ɪˈneɪt','जन्मजात','inborn or natural','inborn','acquired','Some reflexes are innate.'],
['proficient','prəˈfɪʃənt','दक्ष','skilled and competent','skilled','incompetent','She is proficient in Excel.'],
['reticent','ˈretɪsənt','कम बोलने वाला','unwilling to speak freely','reserved','outspoken','He was reticent during discussion.']
];
const starterQuestions=[
{id:'q1',subject:'Mathematics',topic:'Percentage',type:'MCQ',difficulty:'Easy',verified:true,q:'25% of 240 = ?',options:['40','50','60','80'],answer:2,explanation:'240×25/100=60',whyWrong:['40 corresponds to 1/6, not 25%.','50 is not 1/4 of 240.','','80 is one-third of 240.'],concept:'Percentage of a quantity.'},
{id:'q2',subject:'Mathematics',topic:'Percentage',type:'MCQ',difficulty:'Medium',verified:true,q:'A value rises from 200 to 250. Increase percentage?',options:['20%','25%','40%','50%'],answer:1,explanation:'Increase 50; 50/200×100=25%.',whyWrong:['20% of 200 is 40.','','40% gives 80.','50% gives 100.'],concept:'Percentage change uses original value as denominator.'},
{id:'q3',subject:'English',topic:'Subject-Verb Agreement',type:'MCQ',difficulty:'Easy',verified:true,q:'The list of books ___ on the table.',options:['are','is','were','have'],answer:1,explanation:'The grammatical subject “list” is singular.',whyWrong:['Attraction to “books” causes this error.','','Past plural does not fit.','Auxiliary does not fit structure.'],concept:'Subject-verb agreement.'},
{id:'q4',subject:'Child Development & Pedagogy',topic:'Piaget',type:'MCQ',difficulty:'Easy',verified:true,q:'Piaget is primarily associated with which area of development?',options:['Cognitive','Only physical','Only language','Only moral'],answer:0,explanation:'Piaget is best known for cognitive development theory.',whyWrong:['','Too narrow.','Too narrow.','Moral development is more directly associated with other frameworks.'],concept:'Cognitive development.'},
{id:'q5',subject:'Science',topic:'Cell',type:'MCQ',difficulty:'Easy',verified:true,q:'The basic structural and functional unit of life is:',options:['Tissue','Cell','Organ','System'],answer:1,explanation:'Cell is the basic structural and functional unit.',whyWrong:['Tissues are groups of cells.','','Organs contain tissues.','Systems contain organs.'],concept:'Cell basics.'}
];
window.SKY_COMPETITION_DATA={categories,subjectMap,examSubjects,genericCore,verifiedTopics,vocabSeed,starterQuestions,levels:['Basic','Foundation','Exam Level','Advanced','Revision','Marathon','Practice Only'],durations:[15,30,45,60,90,120,180]};
})();
