const SUPABASE_URL=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
function send(res,status,obj){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('X-Content-Type-Options','nosniff');res.end(JSON.stringify(obj))}
async function asJson(r){const t=await r.text();try{return t?JSON.parse(t):null}catch{return {raw:t}}}
async function rest(path,opts={}){return fetch(SUPABASE_URL+'/rest/v1/'+path,{...opts,headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json',...(opts.headers||{})}})}
async function rows(path){const r=await rest(path),j=await asJson(r);if(!r.ok)throw new Error(j?.message||j?.error||'Database lookup failed');return Array.isArray(j)?j:[]}
async function verifyPrimaryAdmin(req){const auth=String(req.headers.authorization||'');if(!auth.startsWith('Bearer '))throw Object.assign(new Error('Primary Admin login required'),{status:401});const ur=await fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:SERVICE_KEY,Authorization:auth}});if(!ur.ok)throw Object.assign(new Error('Invalid/expired Admin session'),{status:401});const u=await ur.json(),pr=await rows(`profiles?id=eq.${encodeURIComponent(u.id)}&select=role,status&limit=1`),p=pr[0],role=String(p?.role||'').toLowerCase(),st=String(p?.status||'active').toLowerCase();if(!p||!['admin','super_admin'].includes(role)||['disabled','inactive','pending','suspended','rejected'].includes(st))throw Object.assign(new Error('Primary Admin permission required'),{status:403});const lock=await rows('v95_primary_admin?singleton_id=eq.1&select=user_id&limit=1');if(!lock[0]||String(lock[0].user_id)!==String(u.id))throw Object.assign(new Error('Only locked Primary Admin can manage Student login'),{status:403});return u}
async function getStudent(id){const r=await rows(`students?id=eq.${encodeURIComponent(id)}&select=id,student_name,admission_no,class_name,student_email,student_login_status,student_login_updated_at,status&limit=1`);if(!r[0])throw new Error('Student not found');return r[0]}
async function findAdmission(adm){const r=await rows(`profiles?linked_admission_no=eq.${encodeURIComponent(adm)}&role=eq.student&select=id,email,linked_admission_no&limit=1`);return r[0]||null}
async function findEmail(email){const r=await rows(`profiles?email=eq.${encodeURIComponent(email)}&role=eq.student&select=id,email,linked_admission_no&limit=1`);return r[0]||null}
function loginAlias(student){let code=String(student.admission_no||'').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,48);if(!code)code=String(student.id||'').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,32);if(!code)throw new Error('Student Admission No. required');return `s${code}@student.ldmodern.local`}
async function authCreate(email,password,meta){const r=await fetch(SUPABASE_URL+'/auth/v1/admin/users',{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password,email_confirm:true,user_metadata:meta})}),j=await asJson(r);if(!r.ok)throw Object.assign(new Error(j?.msg||j?.message||j?.error_description||'Student auth create failed'),{status:r.status});return j?.user||j}
async function authUpdate(id,email,password,meta){const body={email,email_confirm:true,user_metadata:meta};if(password)body.password=password;const r=await fetch(SUPABASE_URL+'/auth/v1/admin/users/'+encodeURIComponent(id),{method:'PUT',headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await asJson(r);if(!r.ok)throw Object.assign(new Error(j?.msg||j?.message||j?.error_description||'Student auth update failed'),{status:r.status});return j?.user||j}
async function upsertProfile(id,email,student){const r=await rest('profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({id,email,full_name:student.student_name||'Student',role:'student',status:'active',linked_admission_no:student.admission_no||''})}),j=await asJson(r);if(!r.ok)throw new Error(j?.message||'Student profile link failed')}
async function updateStudent(id,email,status){const body={student_email:email,student_login_status:status,student_login_updated_at:new Date().toISOString()};const r=await rest(`students?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(body)}),j=await asJson(r);if(!r.ok)throw new Error(j?.message||'Student login status update failed')}
module.exports=async function handler(req,res){if(req.method!=='POST')return send(res,405,{error:'POST only'});if(!SUPABASE_URL||!SERVICE_KEY)return send(res,500,{error:'Supabase server environment is not configured'});try{await verifyPrimaryAdmin(req);const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),action=String(body.action||'');if(!['create_or_set_password','reset_password'].includes(action))return send(res,400,{error:'Invalid action'});if(!body.student_id)throw new Error('Student required');const password=String(body.password||'');if(password.length<8)throw new Error('Student Password कम से कम 8 characters का रखें');const student=await getStudent(body.student_id);if(String(student.status||'Active').toLowerCase()==='inactive')throw new Error('Inactive Student login create नहीं किया जा सकता');const alias=loginAlias(student);let prof=await findAdmission(student.admission_no);if(!prof&&student.student_email)prof=await findEmail(String(student.student_email).trim().toLowerCase());if(!prof)prof=await findEmail(alias);const loginEmail=String(prof?.email||alias).toLowerCase(),meta={full_name:student.student_name||'Student',role:'student',linked_admission_no:student.admission_no||'',class_name:student.class_name||''};let authUser,created=false,status='Not Generated';if(prof?.id){authUser=await authUpdate(prof.id,loginEmail,password,meta);status='Regenerated'}else{authUser=await authCreate(loginEmail,password,meta);created=true;status='Generated'}const uid=authUser?.id||prof?.id;if(!uid)throw new Error('Student user id not returned');await upsertProfile(uid,loginEmail,student);await updateStudent(student.id,loginEmail,status);return send(res,200,{ok:true,created,status,login_email:loginEmail,login_id:student.admission_no||'',linked_admission_no:student.admission_no||''})}catch(e){return send(res,e.status||400,{error:e.message||String(e)})}}
